### ISSUE TITLE
Compatibility with AWS Multi-Factor Auth

### ISSUE THREAD

**Issue by lox** [remind101/stacker#106]
I see mention of env variables for AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY, but how about for when AWS_SESSION_TOKEN exists when using MFA?

I couldn't find anywhere in the code where these vars were explicitly referenced, so the standard boto auth mechanism should work, but it doesn't seem to from our tests.

```
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidClientTokenId</Code><Message>The security token included in the request is invalid</Message></Error><RequestId>cdb0b289-67e1-11e5-90fe-17e65d18e686</RequestId></ErrorResponse>
```

**Comment by phobologic** [comment]
Where have you seen the use of `AWS_SESSION_TOKEN`?  I don't see it anywhere in the boto source - I see some mention of a variable with that in boto3, but not the environment variable itself.  Maybe it's a aws CLI thing?

If you've seen it's use with the original boto library let me know where.

That said, I've worked with getting MFA working with boto before - it's not super hard, and definitely something worth doing here.  When I dealt with it before was providing a variable that held the ARN of your MFA, and then asking for your MFA token when you go to make a call with the library.

Anyway, I'll dig more into this - but if you have any reference to using AWS_SESSION_TOKEN in the original boto, please let me know.  Thanks!

**Comment by phobologic** [comment]
It does look like it works with the original boto - but it's not called `AWS_SESSION_TOKEN` it's called `AWS_SECURITY_TOKEN` I believe.  Have you tried that?

**Comment by lox** [comment]
Interesting, I thought that boto was up to date with the AWS SDK standards for authentication, which use AWS_SESSION_TOKEN. Will investigate more, are you guys on the latest boto?

**Comment by lox** [comment]
Gross. https://github.com/boto/boto/issues/3298

**Comment by phobologic** [comment]
Yeah, it doesn't look like the team has updated boto to match that blog post.  What's interesting is that the SDK page for AWS still lists boto as the primary python library, but they haven't yet updated it.  Not sure how to read that.

**Comment by lox** [comment]
Ok cheers, sounds like this is a boto issue anyway, thanks for the prompt response!

**Comment by phobologic** [comment]
No problem - if there's something we can do to make this easier let me know :)
