### ISSUE TITLE
require_stacks tag can get beyond AWS limit for tag value length

### ISSUE THREAD

**Issue by berndtbrkt** [remind101/stacker#108]
When dealing with a large(r) number of stacks, the tag value can grow beyond the AWS limits (particularly the require_stacks tag).  This results in an error in deployment.

I noticed that there is another issue regarding tags (https://github.com/remind101/stacker/issues/44), and a comment that the tags aren't actually used for anything.  Should the tags be nuked (kill two birds)?  I'd be happy to put a pull request together, but I'm not sure what the right approach is.

Hi Mike :).

**Comment by phobologic** [comment]
Yeah - at this point we might as well yank out the require_stacks tag, it's not used for anything, and doesn't appear that it will every actually be very useful.  @mhahn, you don't use this for destroy right?

**Comment by phobologic** [comment]
I think this and #44 were 'fixed' with this update: https://github.com/remind101/stacker/pull/110/files

Closing.
