### ISSUE TITLE
Excessive Memory Consumption

### ISSUE THREAD

**Issue by gcallaghan** [remind101/stacker#111]
As my stacker config grows, the memory consumption has grown significantly. I have a vagrant development environment that is running out of memory when attempting to deploy a stack. I've had to increase my vagrant box memory to 4gb in order to handle a stacker deployment with 17 stacks.

**Comment by phobologic** [comment]
A little more info:

- Does the memory consumption happen all at once, or as stacker runs over time?
- Can I get a little more info about the stacks you're building?  Are you using the blueprints that come with stacker, or are they custom blueprints?  How big are the resulting templates?
- How much memory is in use when you run into these issues?
- What arguments are you running stacker with?
- Does this happen both on first deploy and future updates?

**Comment by dramdass** [comment]
* Does the memory consumption happen all at once, or as stacker runs over time? 
 * All at once after it says "Deploying! Executing Stacker..."
* Can I get a little more info about the stacks you're building? Are you using the blueprints that come with stacker, or are they custom blueprints? How big are the resulting templates?
  * We're doing some custom ones. They are 17 stacks ranging from about 2KB to a couple at 17KB
* How much memory is in use when you run into these issues?
 * PID     USER    PR  NI    VIRT    RES      SHR   S  %CPU %MEM     TIME+ COMMAND
 *  10097 vagrant   20   0 1344212 1.240g   3676 R  99.8     63.5            1:18.89 stacker
* What arguments are you running stacker with?
 * stacker build -r us-west-2 <env path> <yaml path>
* Does this happen both on first deploy and future updates?
 * In my case, future updates
* What version of stacker are you using?
 * 0.5.2

**Comment by phobologic** [comment]
BTW, I've confirmed this, and I've found the issue.  I'm going to be out of town starting tomorrow (Mexico) so won't be able to get back to this till Wednesday, but I've done a bunch of research and attempted a few fixes (that successfully fixed the memory usage, but broke the system in other ways).  Anyway, I'm going to put some notes up here to help me when I can get back to this, or to help anyone who might want to look at it.

So - here's some relevant lines of code:

- Here we create each stack from the Context - passing the context in:
https://github.com/remind101/stacker/blob/master/stacker/context.py#L72

- Here is the Stack object, and you can see the fun comment above the line of code:
https://github.com/remind101/stacker/blob/master/stacker/stack.py#L68

So we're doing a deepcopy on the context, which keeps a list of each stack.  So the first stack ends up with a full copy of the context with no stacks in it.  The second stack ends up with a full copy of the context, but now with a full copy of Stack1 in it, which has a full copy of the context in it... you see where this is going.

The hard part here is deciding just what information we pass down to the blueprint.  I've done a survey of the folks that I know that use stacker quite a bit (@dramdass & @mhahn) as well as looking at Remind's stacks, and the public stacks.  The context is used (in blueprints) for a few things:

- The environment
- The local parameters
- The regular parameters (being used in python code - not great, thats what local parameters were created for, though I get that it's a bit confusing)
- The namespace (which is now in the environment, so really doesn't need to be a separate thing)

I'm trying to find a good separation here that won't break things for folks, but at the same time doesn't involve the issue we're seeing here.

Anyway, if anyone has any ideas let me know- I hope to get back to this soon after Mexico.

**Comment by phobologic** [comment]
BTW, one more bit of pain - here:

https://github.com/remind101/stacker/blob/master/stacker/actions/base.py#L169

We actually iterate over something and modify it in place.  It's a bad idea. I have a change on hand that'll change the way that works (and should make it a bit faster, though without strict ordering).  I haven't tested this fully, but I think this will end up simpler in the long run:

```
def get_stack_execution_order(dependencies):
    """Return the order in which the stacks should be executed.

    Args:
        - dependencies (dict): a dictionary where each key should be the
            fully qualified name of a stack whose value is an array of
            fully qualified stack names that the stack depends on. This is
            used to generate the order in which the stacks should be
            executed.

    Returns:
        array: An array of stack names in the order which they should be
            executed.

    """
    completed = []

    while True:
        remaining = set(dependencies) - set(completed)
        if not remaining:
            return completed
        for stack_name in remaining:
            requirements = dependencies[stack_name]
            # No requirements left for stack_name, add it to completed
            if not set(requirements) - set(completed):
                completed.append(stack_name)
```
