### ISSUE TITLE
Fn::GetAZs only returns VPC's with default subnets

### ISSUE THREAD

**Issue by ejholmes** [remind101/stacker#122]
I don't think this is something that stacker needs to try to handle, but wanted to put it here in case anyone runs into it.

Within the [vpc stack](https://github.com/remind101/stacker/blob/535b64010da02f3ef189235e545944ef4f676b50/stacker/blueprints/vpc.py#L176) we iterate through AZCount and select from `Fn::GetAzs`. However, it's possible that if you ever delete the default subnets in an aws account that this function will not return anything:

From http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html
> For the EC2-Classic platform, the Fn::GetAZs function returns all Availability Zones for a region. For the EC2-VPC platform, the Fn::GetAZs function returns only Availability Zones that have a default subnet unless none of the Availability Zones has a default subnet; in that case, all Availability Zones are returned.

**Comment by phobologic** [comment]
Going to go ahead and close this since there's no much we can do about it - but at least it's documented here if someone goes looking for it.
