### ISSUE TITLE
Empire AMI seems to be targetting old ECS agent (at least for eu-west-1)

### ISSUE THREAD

**Issue by gileze33** [remind101/stacker#134]
It seems like the latest AMI `ami-3cef374f` is targetting ECS agent version `1.4.0` which has some really bad disconnection issues.

Could you walk me through how to update the AMI?

**Comment by phobologic** [comment]
The agent actually gets pulled here:

https://github.com/remind101/empire_ami/blob/master/ansible/roles/aws_ecs/files/etc/init/ecs_agent.conf

Updating that to a newer version should pull in a newer version of ECS.  Of course if there have been any config changes, etc, they need to be handled, and then verifying that it works.  You should be able to see all the things relating to ecs's agent in: 

https://github.com/remind101/empire_ami/blob/master/ansible/roles/aws_ecs

I'm hoping to do a new release of the AMI soon (next week?) which will include a newer ECS agent and the latest empire release as well.

**Comment by phobologic** [comment]
Hey @gileze33 - just created this PR:

https://github.com/remind101/stacker_blueprints/pull/6

Check it out, let me know if that works for you.  Thanks!

**Comment by phobologic** [comment]
This should be fixed in the latest stacker_blueprints.
