### ISSUE TITLE
Make namespace optional?

### ISSUE THREAD

**Issue by ejholmes** [remind101/stacker#137]
If you're using separate AWS accounts for each "meta" stack, having a namespace doesn't add much value, and actually makes it harder to search through the cloudformation generated names for things.

What do you think about making the namespace optional and if not provided, just upload the templates direct to cloudformation instead of s3 to avoid having to create the s3 bucket before hand?

**Comment by phobologic** [comment]
The reason we use S3 is to make sure that any template you upload will work - without S3 you are limited on the size of the template you can upload.  I think this is less of a problem these days, though I haven't looked in a while.

This could be quite a bit confusing though, especially when some hooks/blueprints make use of the namespace for automatic naming/namespacing of various resources (s3 buckets, iam roles that are created outside of Cloudformation, etc).  Not sure it'd give much benefit and doesn't seem to cost much as is.

**Comment by ejholmes** [comment]
Makes sense, although, it would be nice to at least be able to decouple the namespace from the s3 bucket (or just upload direct to cloudformation) otherwise you get into a scenario where you can't use the namespace you wan't because the bucket is already taken.

**Comment by mhahn** [comment]
It is annoying that you wouldn't be able to use a specific namespace because someone is already using that.

If we submit directly to s3, we have to be under the 51,200 byte limit, which I wouldn't want to deal with.

What if we add an optional parameter to the config like `s3_suffix:` which you could use to provide a random value that would only be used when creating the s3 bucket name?

**Comment by mhahn** [comment]
I was cleaning up some of the docs and found we already support this: http://stacker.readthedocs.io/en/latest/config.html#s3-bucket.
