### ISSUE TITLE
Run in existing environment

### ISSUE THREAD

**Issue by jonatanblue** [remind101/stacker#139]
The current example (in ``conf/example.yaml``) seems to assume that I will set up everything using stacker. Do you have any examples of a stack for an existing environment? For example, if I already have a VPC configured, and want to add a subnet using stacker, how would I specify the VPC ID?

Do let me know if there's a better place to ask these kinds of questions (irc/slack/mailinglist).

**Comment by phobologic** [comment]
In general I think most people do use stacker that way - they let it manage the whole stack.  That said, it should be pretty easy to get it to work with existing resources. You won't be able to use the `stack::resource` reference in Parameters, but you can still provide the values yourself.  So f something is asking for the VPCId, you'd just provide it manually for that value.  for example:

https://github.com/remind101/stacker/blob/master/conf/example.yaml#L24

```
  VpcId: vpc::VpcId
```

Would become:

```
  VpcId: vpc-abcdef12 # or whatever the VPC Id is
```

I'm not sure that all the existing blueprints will work right out of the gate that way - some of the older ones (vpc, asg, etc) were pretty integrated.

Easy thing first: Issues are just fine for these sorts of things, though we do have a slack group you can join.  If you'd like an invite, go ahead and email me at loki77@gmail.com
