### ISSUE TITLE
Add a --dryrun flag

### ISSUE THREAD

**Issue by ejholmes** [remind101/stacker#152]
Sometimes, I just want all the templates to be generated as a way of syntax checking, which would provide faster feedback than deploying (and would also make it useful as a test in CI).

**Comment by phobologic** [comment]
I've previously wanted a `dump` command that dumped all the templates to a directory so that we could analyze them.  I think that might be a good place for this type of thing - maybe just an option to build the templates but not dump them anywhere.

**Comment by phobologic** [comment]
I think this is basically handled by the new `--dump` option to build.  Closing.
