### ISSUE TITLE
Move to local parameters

### ISSUE THREAD

**Issue by mhahn** [remind101/stacker#175]
We've talked about this a bunch, we should move to local parameters since we don't actually leverage the parameters being a part of the cloudformation template.

When we make this move, we should also drop defining parameters as a class variable. It makes subclassing a pain, ie:

```
    def get_local_parameters(self):
        params = getattr(self, "LOCAL_PARAMETERS", {})
        params.update({
            "DataDogAPIKey": {
                "type": str,
                "description": "API key for Data Dog",
            },
            "DataDogTags": {
                "type": str,
                "description": "Tags to include for Data Dog",
            },
        })
        setattr(self, "LOCAL_PARAMETERS", params)
        return super(Base, self).get_local_parameters()
```

**Comment by mhahn** [comment]
local parameters also doesn't handle resolving dependencies from other outputs

**Comment by mhahn** [comment]
I'd like to move away from the current `PARAMETERS` and `LOCAL_PARAMETERS` and move to a new concept of parameters with the following behavior:
- should be a simple python dictionary of values. this lets us leverage the YAML config to pass complex types (lists/dicts). (similar to `LOCAL_PARAMETERS`)
- should support resolving stack outputs, similar to `PARAMETERS`
- subclassing should be straightforward
- referencing within the blueprint should be straightforward

We can make this work in a backwards compatible way by leaving `PARAMETERS` and `LOCAL_PARAMETERS` the way they are (with plans to deprecate in the future) and move to this UX:

```
from stacker.blueprints.base import Blueprint


class NewBlueprint(Blueprint):

    BLUEPRINT_PARAMETERS = {
        'SecurityGroups': {
            'type': list,
        }
    }

    def create_template(self):
        # get_parameters returns `BLUEPRINT_PARAMETERS` by way of the
        # `defined_parameters` which makes it easy for subclasses to add
        # parameters
        params = self.get_parameters()
        for sg in params['SecurityGroups']:
            print sg


class NewSubclassBlueprint(NewBlueprint):

    def defined_parameters(self):
        params = super(Blueprint, self).defined_parameters()
        params['NewSubclassParameter'] = {
            'type': str,
            'description': 'Parameter',
        }
        return params

    def create_template(self):
        super(NewSubclassBlueprint, self).create_template()
        params = self.get_parameters()
        print params['NewSubclassParameter']
```

**changes**:

- new `BLUEPRINT_PARAMETERS` class variable. The current `PARAMETERS` and `LOCAL_PARAMETERS` are hard to subclass because there is no method which just returns the dictionary of parameters that you can build upon. But it does make it less verbose when you're defining parameters for a simple blueprint. Having to define a function to return the dictionary would be annoying. Once we deprecate the existing CF only `PARAMETERS` we can rename this to `PARAMETERS`.
- new `def defined_parameters` method will just return `BLUEPRINT_PARAMETERS` by default and will make it easy for subclasses to build up the parameter values
- new `def get_parameters` will return the parameters that have been built up by `defined_parameters` and had any of the values that depend on other stacks resolved.

**Comment by phobologic** [comment]
@acmcelwee @troyready - you guys have been pretty active here lately, not sure if you're on the slack team, but thought I'd ping you to see if you have any opinions about this.  Thanks!

**Comment by troyready** [comment]
My only thoughts are way out on the bikeshed. Seems good to me conceptually.

**Comment by mhahn** [comment]
@troyready bikeshed comments are welcome too ;)!

**Comment by acmcelwee** [comment]
I like it. I sort of did this in our company-specific base blueprint to allow extension of the parameters that parent blueprints might've added.

```python
class DataworldBlueprint(Blueprint):
    PARAMETERS = dict(params.base_params())

    def add_parameters(self, parameters_list):
        self.PARAMETERS = dict(
            self.PARAMETERS.items() +
            parameters_list
        )
```

👍 from me
