### ISSUE TITLE
Allow cross-namespace output gathering for parameters

### ISSUE THREAD

**Issue by phobologic** [remind101/stacker#184]
This comes from @acmcelwee in https://github.com/remind101/stacker/pull/169#issuecomment-233201214.  This is something I've thought about before, but hadn't come up with a good conclusion.

One idea is that we could have stacker attempt to find the stack with the namespace, and if that fails fall back to looking for the stack without the namespace.  The only downside to that is that it feels like it could do something accidentally, but in that case I get the feeling it'd just fail to create the stack at all.

Another option is to come up with another syntax that indicates to look outside of the stack definition at stacks.  not sure what that syntax would be.

CC: @ejholmes @mhahn

**Comment by phobologic** [comment]
And I realized now that I missed  @acmcelwee 's proposal for a syntax - basically a leading `::` in front would indicate that it's a fully qualified stack name - that seems fine to me.

**Comment by acmcelwee** [comment]
@phobologic, thanks for pulling this over. It hasn't been a blocker for me yet, so I haven't spent any brain cycles on it lately. I'm quoting your contract expectation from [#169 (comment)](https://github.com/remind101/stacker/pull/169#issuecomment-234603481)

> I don't think it has to be that complicated - the contract could be that if you specify a full stack name for an Output that it no longer guarantees much other than it's in a 'consistent' state (ie: UPDATE_COMPLETE, CREATE_COMPLETE, etc).

The combination of a leading `::` for fully-qualified stacks + the contract stated above seems like enough to provide a lot of useful functionality without complicating things.

**Comment by mhahn** [comment]
@acmcelwee can you take a look at: https://github.com/remind101/stacker/pull/202 and see if that addresses your issue here?
