### ISSUE TITLE
Pass stacker bucket name as hook parameter to allow uploading of secondary artifacts 

### ISSUE THREAD

**Issue by danielkza** [remind101/stacker#207]
I would like to upload some files to S3 (more specifically, a script to be used with Cloudformation::Init) to be used in my stacks, and it would be nice to be able to place them in the same bucket as stacker to avoid creating more. Right now the hook functions do not have access to `context.bucket_name`, but I think it would be useful.

**Comment by mhahn** [comment]
our current `handle_hooks` logic looks like:

```
            result = method(
                region,
                context.namespace,
                context.mappings,
                context.parameters,
                **kwargs
            )
```

so we pass a lot of stuff from the context to the method already.

I think this should really just be

```
result = method(context)
```

and `region` should be on the context object.

For 1.0 we can update the hook handler to just take the context, for 0.8.2 we can just pass context as a kwarg.

**Comment by mhahn** [comment]
Looking through it I guess `region` comes from provider which makes sense, I think something similar to what we've done for lookups where these receive:

`result = method(provider=provider, context=context)`

**Comment by mhahn** [comment]
https://github.com/remind101/stacker/pull/234 is a version that will work for 0.8

**Comment by danielkza** [comment]
Sorry for taking so long to respond, but this looks like exactly what I needed. Thanks!
