### ISSUE TITLE
Having a slash inside a lookup seems to cause infinite recursion

### ISSUE THREAD

**Issue by ttarhan** [remind101/stacker#213]
While working in the ${file...} lookup, I discovered that having a slash inside the lookup, such as:

`${file parameterized-b64:file://userdata.txt}`

causes infinite recursion in Variable.resolve, on line 118 (while self.lookups). Simply removing the slashes in the path above avoids the problem.

I haven't looked into the root cause yet.

**Comment by phobologic** [comment]
I'm taking a guess, but it's likely due to this line: https://github.com/remind101/stacker/blob/master/stacker/variables.py#L11 - you might need to include `\/` in the idpattern.  @mhahn will know best.

**Comment by ttarhan** [comment]
@phobologic indeed, that fixes it. I'll put in a simple PR just for that fix right now.
