### ISSUE TITLE
Should blueprint variables accept non-python built in types

### ISSUE THREAD

**Issue by phobologic** [remind101/stacker#217]
Right now we only accept basic python types and CFNTypes due to this code:

https://github.com/remind101/stacker/blob/378d0bfb989900a4c688cc51f25f7702cdbfac87/stacker/blueprints/base.py#L285

That works great, but what if we want more specific types.  For example, I am building a blueprint that will allow you to build an SNS queue with multiple subscriptions.  My idea for the config would be something like:

```
  topics:
    topic1:
      - subscription1
      - subscription2
```

Right now I can only define `topics` as a `dict` type, but that leaves a lot of room for error.  Instead, what I'd like to do is provide my own validation function, something like:

```
def validate_topics(value):
    if not isinstance(value, dict):
        raise InvalidVariable("topics must be a dictionary")
    for k, v in value.items():
        if v and not isinstance(v, list):
            raise InvalidVariable("Topics should include a list of subscriptions.")
    return True
```

**Comment by phobologic** [comment]
@mhahn assigning you  just to get your thoughts, you don't have to handle this if you're ok with it, I can write a PR

**Comment by phobologic** [comment]
Talked it over with @mhahn, and I think instead I'm going to work on an optional `validator` setting for Variables, that will let you do custom validation of the contents of the variable.

**Comment by mhahn** [comment]
👍

**Comment by mhahn** [comment]
@phobologic you can close this now right?

**Comment by phobologic** [comment]
Yup, closed.
