### ISSUE TITLE
Unable to export templates using -d

### ISSUE THREAD

**Issue by ttarhan** [remind101/stacker#223]
The -d option to 'stacker build' is broken after the recent variable-related changes. It always fails if there's any lookups:

stacker.exceptions.UnresolvedVariables: Blueprint: "clusterinstance" hasn't resolved it's variables

**Comment by mhahn** [comment]
This is tough with `output` lookups. `dump` is essentially a dry run where we don't submit the stacks to CF. I think I have something that will work if you're using `CFNType`, but there are cases where that will break if you have a blueprint that depends on an output to render.

**Comment by mhahn** [comment]
@ttarhan can you give some context on how you use `-d`?

**Comment by mhahn** [comment]
Have a fix for this in 1.0

**Comment by mhahn** [comment]
Fixed with: https://github.com/remind101/stacker/pull/231
