### ISSUE TITLE
Commands hang with circular variable

### ISSUE THREAD

**Issue by syphon7** [remind101/stacker#228]
Very small issue -

When an output is used as a variable to the stack that creates the output stacker hangs rather than errors.

E.g.
`
-name: main-vpc`
`
   variables:`
`
        TestVar: ${main-vpc::TestVar}
`

This is an invalid variable, but it should detect that rather than hang indefinitely.

**Comment by phobologic** [comment]
@syphon7 thanks for noticing this, will try to get it cleaned up asap.
