### ISSUE TITLE
dump mode of build action won't work with unresolved variables

### ISSUE THREAD

**Issue by troyready** [remind101/stacker#240]
I'm seeing a `stacker.exceptions.UnresolvedVariables: Blueprint: "myblueprint" hasn't resolved it's variables` error when attempting to use the `--dump` option with build.

I looked into how the dump option shortcut works, but it's not clear to me how/where to best fix it.

The blueprint I'm testing with only has VARIABLES defined of CFN parameter types and AWSHelperFn.

**Comment by mchristen** [comment]
I also ran into this... I made a pull request with my quick and dirty fix to it here #243 

Feel free to try it out and see if it also works for you.

**Comment by phobologic** [comment]
@troyready have you given the 1.0.0a1 release a try?  It sounds like, from #243, that this may be fixed already?

**Comment by troyready** [comment]
@phobologic you're right, this is resolved in the 1.0 branch. Thanks @mhahn !
