### ISSUE TITLE
Cut new release 1.0.0a2?

### ISSUE THREAD

**Issue by jonathanunderwood** [remind101/stacker#258]
There's a bunch of fixes in the git branch since release 1.0.0a1 which are important - any chance of cutting another release tarball for PyPi so more bugs get shaken out?

**Comment by phobologic** [comment]
Good call - all set.  1.0.0a2 is out.  Thanks!

**Comment by phobologic** [comment]
Actaully realized I forgot the master merge first, so I've just spun 1.0.0a3 as well.
