### ISSUE TITLE
Set a botocore credential cacher

### ISSUE THREAD

**Issue by ejholmes** [remind101/stacker#284]
The AWS CLI (and by extension, botocore) supports specifying [profiles that can automatically assume a role](http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html). This allows you to do something like this:

```console
$ cat ~/.aws/config
[profile prod]
region = us-east-1
role_arn = arn:aws:iam::1234:role/Stacker
mfa_serial = arn:aws:iam::4321:mfa/user
source_profile = default
$ aws ecs list-clusters --profile prod
```

It's possible to use this with stacker by setting the `AWS_DEFAULT_PROFILE`, since we use boto3. However, when assuming a role with MFA, every request will prompt you for an OTP. When using the AWS CLI, you only get prompted once, [because it sets a credential cache](https://github.com/boto/botocore/commit/2dae76f52ae63db3304b5933730ea5efaaaf2bfc#diff-dcd72ae45553af71f1ceafb2d4ee5dcf) (see the commit description).

It would be nice if stacker did the same caching as well, so you only get prompted for MFA once and temporary credentials are used until they expire.

**Comment by phobologic** [comment]
https://github.com/remind101/stacker/pull/307 - Thanks @ttaub
