### ISSUE TITLE
Latest Dockerfile/Image has errors

### ISSUE THREAD

**Issue by andrewoh531** [remind101/stacker#329]
Just pulled the latest Docker image and tried running a command but getting the following error:

`python: can't open file 'setup.py': [Errno 2] No such file or directory`. 

Latest push was a day ago so may have been something from that.

**Comment by troyready** [comment]
Do you have a `setup.py` file in the directory in which you're running the container?

**Comment by phobologic** [comment]
@andrewoh531  - did you manage to get this working with a setup.py in the base directory?  I think the bigger issue here is just having better documentation/examples on how to use the docker image.  @troyready do you guys use it at all?

**Comment by andrewoh531** [comment]
Sorry I moved on from stacker. It may have been an error on my side and/or lack of documentation. Closing this issue.

**Comment by troyready** [comment]
@phobologic it's really only mentioned by as as a theoretical 'fallback' option / support for older versions . I put a no-op setup.py alongside all of our configurations to support this (since the config yamls specify a local sys_path for the blueprints).

**Comment by phobologic** [comment]
@troyready cool, thanks!
