### ISSUE TITLE
Use default region for s3

### ISSUE THREAD

**Issue by mhahn** [remind101/stacker#33]
If you switch regions but use the same namespace, you'll get conflicts.

**Comment by mhahn** [comment]
should we just create a "s3_conn" property similar to "conn" that uses the default ConnectionManager?

**Comment by phobologic** [comment]
Honestly the only time the s3connection is used is when you setup cfn_bucket, so we can probably just create the connection in there (boto.connect_s3) and use it right away.  After that it's not really useful, as we use cfn_bucket directly, which is a boto.s3.Bucket object, which has all the connection info it needs.

I should probably strip out aws_helper entirely at this point, it's not super useful any longer I don't think.  I'll dig into that more.

**Comment by mhahn** [comment]
yea i looked at the library and it didn't look like it was doing a whole lot

**Comment by phobologic** [comment]
This was fixed.
