### ISSUE TITLE
New Lookup: ami

### ISSUE THREAD

**Issue by discobean** [remind101/stacker#350]
It would be great to have a new lookup like `{ami filter=xyz}` or something similar.

The filter will fetch the lastest AMI ID with a specific search.

For continuity it would be good to build it so the filter is similar that to the one available already in terraform.

**Comment by phobologic** [comment]
Sounds like a useful lookup - not sure we'll have time ourselves to try and get this in for 1.1, but if anyone else is up for it I'd definitely be up for the PR!

**Comment by discobean** [comment]
Sure, I can have a look when we get around to automating this part.

**Comment by danielkza** [comment]
I would love to have this, since I'm working on a [packer](https://packer.io) build hook to generate AMIs.

**Comment by phobologic** [comment]
Closing since #360 was merged!
