### ISSUE TITLE
Combine namespace & environment

### ISSUE THREAD

**Issue by phobologic** [remind101/stacker#37]
Right now the namespace & environment seem excessive together.  Spoke with a few people about this and the current proposal is to combine them - basically do away with the namespace on the command line, and instead require an environment file with each run.  In the environment file, the minimum contents would be something like:

``` yaml
namespace: <namespace>
```

**Comment by phobologic** [comment]
New command would effectively be:

`stacker -r us-east-1 -e conf/stage.env conf/example.yaml`

Seems like getting rid of -e would be nice, since it's required, but not sure if that'd make the CLI more confusing.

**Comment by mhahn** [comment]
fixed with https://github.com/remind101/stacker/pull/72
