### ISSUE TITLE
Content hash in aws_lambda hook non-deterministic?

### ISSUE THREAD

**Issue by ejholmes** [remind101/stacker#370]
Need to investigate this further, but we've noticed that the hash seems to change periodically, or across machines. I think this _might_ be because we hash the zip file itself, which may be including some extra metadata that changes.

Maybe we should hash the included files themselves? Basically:

1. Filter/Exclude files
2. Sort the file names.
3. Hash the file content.
4. Hash the combination of the file hash, and file name

We use this algorithm in another internal build system to produce hashes of a file system that's deterministic across machines. In bash:

```console
find . -L -type f | sort | xargs sha1sum | sha1sum | cut -d ' ' -f 1
```

**Comment by phobologic** [comment]
Yep, your guess is correct - we hash the contents of the zip, but zip files include headers for the last modification time of each file: https://en.wikipedia.org/wiki/Zip_%28file_format%29#File_headers.

**Comment by phobologic** [comment]
@ejholmes check out #372
