### ISSUE TITLE
Cannot destroy individual stack with requires

### ISSUE THREAD

**Issue by sdechgan** [remind101/stacker#384]
I cannot destroy an individual stack that is required by another stack

For example:

Here is my stacker.yml
```
stacks:
  - name: stack1
    class_path: blueprints.application.Application
    enabled: true
  - name: stack2
    class_path: blueprints.s3.Event
    enabled: true
    requires:
      - stack1
  - name: stack3
    class_path: blueprints.api.OpenApi
    enabled: true
    requires:
      - stack1
      - stack2
```

Here is my command
```
stacker destroy --stacks stack3  environments/dev.env stack.yml
```

I get the following error:
```
[2017-05-12T14:53:29] Using Default AWS Provider
Traceback (most recent call last):
  File "~/.pyenv/bin/stacker", line 9, in <module>
    args.run(args)
  File "~/.pyenv/lib/python2.7/site-packages/stacker/commands/stacker/destroy.py", line 35, in run
    action.execute(force=options.force, tail=options.tail)
  File "~/.pyenv/lib/python2.7/site-packages/stacker/actions/base.py", line 124, in execute
    self.run(*args, **kwargs)
  File "~/.pyenv/lib/python2.7/site-packages/stacker/actions/destroy.py", line 100, in run
    plan = self._generate_plan(tail=tail)
  File "~/.pyenv/lib/python2.7/site-packages/stacker/actions/destroy.py", line 56, in _generate_plan
    stacks_dict[stack_name],
KeyError: 'dev-stack2'
```

Isn't that the correct command to delete an individual stack?

**Comment by phobologic** [comment]
I think we could definitely have a better error there, but I think the logic is pretty sound.  If stack3 requires stack2, then you shouldn't be able to destroy stack2 without destroying stack3 as well.

**Comment by sdechgan** [comment]
Shouldn't you be able to delete `stack3` without deleting `stack2`?  Logically, `stack2` doesn't need `stack3` to work properly because `stack3` was the last stack created.

That or I don't understanding is usage of the `--stacks` parameter.

**Comment by ejholmes** [comment]
This looks like a legit bug when specifying `--stacks` with `destroy`, no? It errors out [here](https://github.com/remind101/stacker/blob/master/stacker/actions/destroy.py#L56) when trying to generate the plan.

`stack3` should only depend on `stack2` during a build. During a `destroy` the graph should be transposed, so that `stack2` depends on `stack3`. It's _likely_ that this is already fixed in the DAG branch.

**Comment by aarcro** [comment]
Still busted in 1.1.2 I'd really like to be able to destroy a single stack. Just going to nuke it from CloudFormation directly I suppose.
