### ISSUE TITLE
Plan status clobbers CloudFormation logs

### ISSUE THREAD

**Issue by aarcro** [remind101/stacker#386]
When using -t to tail the CloudFormation logs, you probably don't want to be doing the Cursor.UP magic in LogLoopStreamHandler as it writes over the CF logs.

**Comment by ejholmes** [comment]
Hey @aarcro. I just opened https://github.com/remind101/stacker/pull/414 to fix this.

One quick workaround for the time being is to pipe to `cat -`, which will disable the loop logger:

```
stacker build dev.env stacker.yaml | cat -
```
