### ISSUE TITLE
UX flow with initial stacker build failures and rollbacks

### ISSUE THREAD

**Issue by GarisonLotus** [remind101/stacker#393]
# Feedback welcome - this is an open discussion item
I wanted to start a conversation regarding this: In stacker, when I run a stacker build on an initial deployment of a brand new stack that happens to fail, the stack itself goes into a ROLLBACK_IN_PROGRESS status eventually ending up in a ROLLBACK_COMPLETE state with no way to run build again.  This is the expected behavior with stacker as it matches cloudformation.

However for a user who is an AWS novice, getting out of this state with stacker... is a different experience than someone uploading templates in the CFN console directly.

I have had several conversations with our in-house development team about their use of Stacker around their user experience they have had with it since a lot of them are using it now for the first time. If a developer with no AWS or CFN experience were to run into this problem, stacker actually appears to hinder their progress moreso vs CFN natively. Let me explain why by going over both flows:

## CFN console native UX workflow
In the AWS console, if I were to incorrectly create a template that fails, I get stuck in a ROLLBACK_IN_PROGRESS, followed by a ROLLBACK_COMPLETE state that is unrecoverable. I can then look at the template itself to figure out the problem or the AWS console to determine what needs to be fixed. After resolution and when I got to resubmit, the UI doesn't allow me to perform the "update stack" operations, instead only allows you to select "delete stack", thus walking you through their intended flow of deleting the stack first. 

In this flow (although not perfect), a user is pretty much told... you must delete this stack before you can try again. It's the only option, so it's natural for a user to chose it.

## Stacker UX workflow
In stacker, when I do a stacker build of that same mistake CFN deployment (via a similar mistake in the blueprint let's say), I get told that the stack is in a ROLLBACK_IN_PROGRESS state, but nothing else.  I can then look at the template itself to figure out the problem, or the AWS console, just like with CFN natively.  When I go to resubmit via stacker build, I get told an unfriendly ` An error occurred (ValidationError) when calling the CreateChangeSet operation` exception due to the stack being actually in a "ROLLBACK_COMPLETE" state and I have to figure out what is going on and how to fix it.

These are very different experiences.

## UX flow issues with stacker

So, I have two issues I can see with the stacker the above workflow:

- The user is never told the actual state the stack eventually ends up in. They are shown that a rollback is in progress, but not that they have to do something above and beyond fixing their template due to it actually being in a rollback complete state.

- On the next build, the user is sent on a red herring trip to search google for whatever `CreateChangeSet operation` means.

Both of these result in a bad first experience by a novice user.

Thoughts?

**Comment by GarisonLotus** [comment]
Some ideas thrown around by @troyready and I at Sturdy:  

- Upload a simple template that will always succeed first before submitting the stack, so the rollback has somewhere to go and allows a update stack operation. Kind of like what [serverless](https://github.com/serverless/serverless) does. (They submit a template first to create an S3 bucket, then perform an update against the stack.)

- Catch the exception, go interactive, and offer to delete the stack?  I haven't checked the source code, but perhaps only if we know it's a new stack that will end up in that ROLLBACK_COMPLETE state.

- Catch the exception, then simply tell a user that the stack might need to manually be deleted due to CFN limitations with some possible AWS CLI command examples.

**Comment by GarisonLotus** [comment]
Related to issue #8

**Comment by phobologic** [comment]
Thanks @GarisonLotus @troyready  - this is definitely a pain point.  Having stacker behave intelligently when a stack goes into a "bad state" is something I'd love to do, but it does introduce some complexity (not that I'm opposed).  Let me think about this some more - but all of your suggestions sound better than our current state.

**Comment by danielkza** [comment]
Is it possible to detect if a stack has failed when running it's initial setup? It's a pretty annoying case that I run into pretty often. I make some mistake in the initial version of the stack, but I have to manually delete it in the console just to re-run stacker after a fix. Since there should be no resources left at all (since they didn't exist before the first run), it should be safe to forcefully re-create the stack.

**Comment by GarisonLotus** [comment]
@danielkza - unfortunately, AWS doesn't give us many options here.  If your initial stack fails, the only option you have, is to delete it... even in the console.  Yes it's annoying, and that's what this issue is asking to fix. 

A bunch of developers I work with have chosen Serverless Framework when they had the option, over stacker, because of this issue... so I understand. (Serverless got around this in an interesting way. I'm not sold on their method for stacker however.  Seems wasteful.)

**Comment by danielkza** [comment]
Could we tag the stack with a marker indicating it is the first time it is being run, and delete it automatically if it fails *and* has the marker?

**Comment by troyready** [comment]
I think it'd be best to have that be a query to the user to delete it, but yeah I agree that automating it would be good.

**Comment by danielkza** [comment]
Maybe we could overload `--force` to allow deleting a stacked that failed its initial run.

**Comment by phobologic** [comment]
Fixed in #473
