### ISSUE TITLE
Global config

### ISSUE THREAD

**Issue by LyndonHook** [remind101/stacker#402]
It would be useful to set some top level configs on a global level. I'm not sure about all top level configs but "stacker_bucket" and "tags" (used for deployment branch and commit hash) are the same across all of our YAML files. What about adding a global config file for these? It removes the repetition and can be used to enforce global tagging standards on all blueprints etc?

**Comment by phobologic** [comment]
Hey @LyndonHook - thanks for the Issue, but I'm not sure exactly what you mean by a "global level".  Do you mean you want to be able to access top-level settings in your stacks themselves without repeating them?  or something else?

**Comment by LyndonHook** [comment]
A global config file for the top level YAML keywords. For example if I wanted to set the same stacker_bucket value for all my YAML configs I currently have to go through every YAML file and add the same value to each. It'd be nice to have a single global config for these situations.

**Comment by phobologic** [comment]
@LyndonHook makes sense - I think this sort of relates to my answer in #403 - at this point a pre-processor may be the best bet.  Otherwise it makes things a bit more complicated, and I think config can be complicated enough :)  Does that sound valid to you?

**Comment by LyndonHook** [comment]
Definitely valid. Thanks for the quick response 👍

**Comment by phobologic** [comment]
Closing this - I think the pre-processor, as well as the ability to actually specify `-` as the stacker config file (which uses stdin) should be the best way to handle this without introducing more complexity to stacker's config handling.
