### ISSUE TITLE
More layered environment configs

### ISSUE THREAD

**Issue by LyndonHook** [remind101/stacker#403]
We are trying to create blueprints that can be reused across many applications. This generally means a lot of variables in the YAML file with environment configs. The problem is we need more layers in our config. We don't want to force the inclusion of all variables for every application. Some applications might require more variable changes than others. Some might not need to change any of the defaults.

The current layering is:
Defaults -> YAML -> ENV

We need something like:
Defaults -> YAML -> ENV -> Application Defaults -> Application ENV

Would adding multi level environment configurations be out of the question? They would load hierarchically meaning the more specific config would override the less specific ones.  Or is there an alternative solution?

**Comment by phobologic** [comment]
I could see having multiple environment files.  I don't think there'd be a good way to define "specificity" in the current layout (environment files are just key/value pair files), and I think there'd have to be a good reason to complicate that more (it used to be YAML, but interpreted YAML going into interpreted YAML leads to all sorts of annoying "features").

That said, you could just make it so there are multiple environment files - and they overwrite the values as you move left to right.

The big issue right now is that the environment file is only a single argument, and doesn't require a flag.  It would be a large change to change that.

Traditionally, in the past, when we've talked about making this all that much more complicated, we've instead leaned on the use of some shell trickery `stacker build <(my_env_generator.py) ./stacker.yaml` - then you can use whatever logic you want (and call the script whatever you want) when compiling an environment file.

**Comment by LyndonHook** [comment]
Thanks @phobologic. I suspected we would have to do some preprocessing of our own before passing the configs to stacker. I understand that this kind of structure would complicate what currently is a nice easy to understand config structure. We already have a shell script to simplify the execution and enforce some standards. I'll look into adding some kind of config consolidator into that.

**Comment by phobologic** [comment]
Cool, yeah, I think the `<()` trick in bourne shell makes it pretty nice as well, and it keeps stacker out of complicated config management games.  Let me know if this becomes too cumbersome for you though, I'm not against this idea, it's just not high on the list of things that I think stacker needs/needs to have fixed for us, and I'd want to get the community involved with figuring out the right format for all this.  I'm going to go ahead and close it, but feel free to re-open if you think it should stay open!

Thanks again.  Also, you should join the Slack Community - it's a great place to discuss ideas/issues like this with folks that use stacker a bunch every day :)

**Comment by LyndonHook** [comment]
I'd love to join Slack but unfortunately its blocked at my workplace. I'll also talk to my team about our options, the end result might be that we fork the repo and attempt our own implementation. We'll definitely try and involve the community on the best implementation if we do.
