### ISSUE TITLE
AttributeError when class_path is incorrect 

### ISSUE THREAD

**Issue by GarisonLotus** [remind101/stacker#421]
Wondering if we should catch this and make the UX a little cleaner for thouse who don't know Python well.  A developer I was working with tried (for way too long) to get their YAML config working, and weren't able to understand the below error message.  This was caused by a typo in the stack class path. Easy fix, but just a time waste as I wasn't available to immediately help and they couldn't understand and ended up giving up on until I was available to help.

provided: `class_path: blueprints.create`

Correct class_path: `class_path: blueprints.Instance.create`

15:37:57 Traceback (most recent call last):
15:37:57   File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/bin/stacker", line 6, in <module>
15:37:57     exec(compile(open(__file__).read(), __file__, 'exec'))
15:37:57   File "/home/csweb/.pip/src/package/scripts/stacker", line 9, in <module>
15:37:57     args.run(args)
15:37:57   File "/home/csweb/.pip/src/package/stacker/commands/stacker/build.py", line 52, in run
15:37:57     dump=options.dump)
15:37:57   File "/home/csweb/.pip/src/package/stacker/actions/base.py", line 124, in execute
15:37:57     self.run(*args, **kwargs)
15:37:57   File "/home/csweb/.pip/src/package/stacker/actions/build.py", line 283, in run
15:37:57     plan.execute()
15:37:57   File "/home/csweb/.pip/src/package/stacker/plan.py", line 267, in execute
15:37:57     if not self._single_run():
15:37:57   File "/home/csweb/.pip/src/package/stacker/plan.py", line 227, in _single_run
15:37:57     status = step.run()
15:37:57   File "/home/csweb/.pip/src/package/stacker/plan.py", line 74, in run
15:37:57     return self._run_func(self.stack, status=self.status)
15:37:57   File "/home/csweb/.pip/src/package/stacker/actions/build.py", line 209, in _launch_stack
15:37:57     stack.resolve(self.context, self.provider)
15:37:57   File "/home/csweb/.pip/src/package/stacker/stack.py", line 154, in resolve
15:37:57     self.blueprint.resolve_variables(self.variables)
15:37:57   File "/home/csweb/.pip/src/package/stacker/stack.py", line 111, in blueprint
15:37:57     blueprint_class = util.load_object_from_string(class_path)
15:37:57   File "/home/csweb/.pip/src/package/stacker/util.py", line 259, in load_object_from_string
15:37:57     return getattr(sys.modules[module_path], object_name)
15:37:57 AttributeError: 'module' object has no attribute 'create'

**Comment by phobologic** [comment]
Definitely, that's a pretty crappy exception.

**Comment by GarisonLotus** [comment]
I looked into this today, turns out this specific error is just in staker 1.0.2... master has a different and much better error.

I'm going to close this issue because of this. 

Stacker 1.0.2:
`AttributeError: 'module' object has no attribute 'something'`

From Master as of today:
`AttributeError: Stack class blueprints.CreateFunction does not have a "rendered" attribute.`

So, unless you disagree, nothing to see here.
