### ISSUE TITLE
Better functional testing suite

### ISSUE THREAD

**Issue by ejholmes** [remind101/stacker#437]
We've talked about this internally a bit. We definitely need a better functional testing suite that actually exercises all of the stacker commands. Even just some "sanity" tests would provide a lot of value, and prevent breakages in commands that don't get run manually very frequently.

**Comment by phobologic** [comment]
I agree - I'd love to discuss this more.  It'd be good to come up with an initial implementation list.

**Comment by ejholmes** [comment]
We now have a functional test suite.
