### ISSUE TITLE
update_stack does not modify tags

### ISSUE THREAD

**Issue by phobologic** [remind101/stacker#44]
https://github.com/boto/boto/issues/2032

Looks like this isn't even possible in the Cloudformation API, which is frustrating. It basically means that we can't trust the tags of a stack - and certainly can't rely on them for anything.

Fortunately we don't currently rely on the tags for anything, but it was planned to use the dependent stack tag when writing code to destroy stacks.  Frustrating.

**Comment by phobologic** [comment]
Fixed via https://github.com/remind101/stacker/pull/110/files, closing.

**Comment by ferrants** [comment]
it's possible as of february and now works in boto

**Comment by phobologic** [comment]
Thanks @ferrants - we were actually just talking about this this week after I saw they announced you can do this along with the new Change Sets.  We'll probably re-implement this soon :)
