### ISSUE TITLE
stacker script doesn't work out of the box on Windows

### ISSUE THREAD

**Issue by troyready** [remind101/stacker#441]
Windows doesn't do the right thing with [scripts/stacker](https://github.com/remind101/stacker/blob/1.0.4/scripts/stacker) -- just having the shebang at the top of the file doesn't get the python interpreter invoked.

Looks like awscli handles this by shipping a [separate invocation script for windows](https://github.com/aws/aws-cli/blob/1.11.121/bin/aws.cmd).

**Comment by troyready** [comment]
In PowerShell, a workaround for this is to set an alias in your PowerShell profile: ```Add-Content $PROFILE "`nfunction stacker { python c:\Python27\Scripts\stacker `$args }"```

**Comment by phobologic** [comment]
#447 didn't fix this - but did fix an installation issue on various platforms.  Re-opening this in case someone wants to tackle it - I don't have access to a windows machine to work on this myself.
