### ISSUE TITLE
VPC creation error when creating a stack in us-west-2

### ISSUE THREAD

**Issue by brianz** [remind101/stacker#45]
I used the standard `conf/empire/empire.yaml` file and launched a stack with the following command:

```
stacker -e example.env -r us-west-2 brianz.bz empire.yaml
```

The VPC failed to create with the following error:

```
CREATE_FAILED	AWS::EC2::Subnet	PrivateSubnet3	Template error: Fn::Select cannot select nonexistent value at index 3
```

**Comment by phobologic** [comment]
This is likely due to us-west-2 not having 3 VPC-able Availability Zones.  Maybe using all 4 is too aggressive - I wish Amazon gave a better API for this kind of stuff.

Thanks!

**Comment by phobologic** [comment]
This was actually 'fixed' in https://github.com/remind101/stacker/commit/9f4ae195c01453ee90c5e2b5dbcee978a5374d8c#diff-8f84670404b5e0466057d169e260c840 - closing.
