### ISSUE TITLE
Add an optional description to stacks

### ISSUE THREAD

**Issue by colwilson** [remind101/stacker#475]
Can we have the option to add a description to a stack?

```
 - name: Buckets
    class_path: stacker_blueprints.s3.Buckets
    description: 'Ingestion buckets'
```

**Comment by phobologic** [comment]
@colwilson it should be possible - kind of interesting, the description is actually provided by the template itself.  What would you imagine the behavior would be if the blueprint/template had a description, but you put one in the config?  Should the config win, or the blueprint/template?

Thanks for the request!

**Comment by colwilson** [comment]
Yes I think the config should override a default in the template.

**Comment by phobologic** [comment]
Hey @colwilson - see #477 for a first stab at this.

**Comment by colwilson** [comment]
Looks good to me. Good work!
