### ISSUE TITLE
Build should fail when duplicate stack names exist in a template

### ISSUE THREAD

**Issue by justinkillen** [remind101/stacker#491]
If/when a template has the same stack defined twice (as happens with a bad copy/paste), it should fail validation and abort the run.

**Comment by phobologic** [comment]
Thanks @justinkillen!

**Comment by russellballestrini** [comment]
@phobologic I would like to try to tackle this.

**Comment by russellballestrini** [comment]
@justinkillen what version of stacker are you running and is your YAML `stacks` stanza a `dict` or a `list` of `dicts`?

I think #500 will fix your issue but I need a bit more info to know for sure.

**Comment by justinkillen** [comment]
We were using 1.0.  Updated to 1.1.2 and can confirm that it is fixed.

**Comment by russellballestrini** [comment]
@justinkillen thank you for following up!
