### ISSUE TITLE
inconsistent postgres names

### ISSUE THREAD

**Issue by mhahn** [remind101/stacker#52]
https://github.com/remind101/stacker/blob/master/stacker/blueprints/postgres.py#L9
https://github.com/remind101/stacker/blob/master/stacker/blueprints/postgres.py#L11

create something like:

PostgresRDSapiRdsDb
RdsSGapiRdsDb

the name should always go in the front to stay consistent with other camel cased names.

**Comment by mhahn** [comment]
i don't think this is going to be a backwards compatible change

**Comment by mhahn** [comment]
this is one reason I would push for these blueprint constants being properties of the class. if i wanted to customize these names, i could easily subclass the blueprint and change them to whatever i wanted.

**Comment by phobologic** [comment]
One thing I've started to realize is that all the 'blueprint' specific naming of things isn't as important.  The resource names we give things just have to be unique *inside* a template, not unique across all templates.  So naming something PostgresRDSapiRdsdb doesn't make sense, unless we plan on having multiple resources of that type in the blueprint, which we usually don't.  That means you could name it something simple, like `DBInstance` and be done with it.

Unfortunately changes like this aren't backwards compatible.  It almost makes me want to start a whole new set of blueprints with changes like this.

**Comment by mhahn** [comment]
yea, i like being able to see the names on all the aws entities and be able
to trace that back to the stack. i really wish we could just do
"api-postgres-rds" but they don't allow hyphens :(

**Comment by phobologic** [comment]
Honestly I don't think this is ever going to get changed.  We can try to be better about it going forward, but this isn't really a priority for fixing old resources.  It'd also cause updates on resources that could break things.  Going to close it.
