### ISSUE TITLE
Supporting eu-west-1 in the empire build

### ISSUE THREAD

**Issue by gileze33** [remind101/stacker#80]
I've done the work locally to support eu-west-1 for the stacker empire build but that involved reducing the number of AZs from 4 to 3 (as eu-west-1 only has 3). 

I'd like to give the updates back to you, but is there a way to add conditional logic into the conf/empire/empire.yaml file to allow 4 everywhere but in eu-west-1?

**Comment by phobologic** [comment]
So this is a problem for multiple regions - us-west-1 in my account, for example, only has 2 subnettable zones.

The AZCount thing has always been a little hacky, which was why we ended up adding the local parameters feature: https://github.com/remind101/stacker/pull/61

Let me think about this a bit.  I have code that can figure out how many subnettable zones are available in a given region, but I really need to figure out where the right place for that would be.  Also, we probably want to leave it configurable, so people can choose less zones than the max.

I'll try to come up with something today.

**Comment by gileze33** [comment]
Maybe a way of saying 'up to 3'? Something like "^5"?

**Comment by phobologic** [comment]
So I can't think of a great way to do this 'automatically' with the way things currently are- the blueprint is where the logic happens that uses the AZCount, and the blueprint (purposefully) doesn't have access to the provider.

At this point I think it's best to make AZCount a variable inside the environment file, default it to 2, and leave a comment with detailed instructions about updating it to higher values (no more than 4, and no more than your individual region can handle).  Also probably worth saying something like "We suggest, in a production environment, that you increase this to as many as you possibly can for the most redundancy."

Does that seem like a decent enough workaround, @gileze33 ?

**Comment by gileze33** [comment]
Sounds like a very good work around. I was tempted to submit a PR with it set to 3 but wasn't sure how you guys would react :)

**Comment by phobologic** [comment]
https://github.com/remind101/stacker/pull/82 - let me know if the wording isn't clear enough, or if you think there's something I missed.  I'm not closing this, because in order to get eu-west-1 in there we need to finish the empire_ami stuff, but I think we're getting close!

**Comment by phobologic** [comment]
Hey @gileze33 - I've started copying the empire_ami to eu-west-1 with this update: https://github.com/remind101/empire_ami/pull/13

Was there any other work, other than the change to the # of AZs in the stacker empire config, that you needed to make empire work in eu-west-1?  If not, I'll be updating the stacker config with the eu-west-1 AMI.  Thanks!

**Comment by gileze33** [comment]
Here's the diff from my changes:

diff --git a/conf/empire/empire.yaml b/conf/empire/empire.yaml
index b958381..65d133a 100644
--- a/conf/empire/empire.yaml
+++ b/conf/empire/empire.yaml
@@ -48,6 +48,10 @@ mappings:
       NAT: ami-2dae821d
       ubuntu1404: ami-f15b5dc1
       empire: ami-85ede7b5
+    eu-west-1: 
+      NAT: ami-ef76e898
+      ubuntu1404: ami-47a23a30
+      empire: ami-984c13ef
 
 # Many stacks need these settings, or a subset of them, from the VPC -
 # this makes it easy to pass them around. Stacker will drop unused Parameters
@@ -76,10 +80,10 @@ stacks:
       #       Also you need at least 2 AZs in order to use the DB because
       #       of the fact that the DB blueprint uses MultiAZ
       # Note: You will create a NAT instance PER Availability zone.
-      AZCount: 4
+      AZCount: 3
       # Enough subnets for 4 AZs
-      PublicSubnets: 10.128.0.0/24,10.128.1.0/24,10.128.2.0/24,10.128.3.0/24
-      PrivateSubnets: 10.128.8.0/22,10.128.12.0/22,10.128.16.0/22,10.128.20.0/22
+      PublicSubnets: 10.128.0.0/24,10.128.1.0/24,10.128.2.0/24
+      PrivateSubnets: 10.128.8.0/22,10.128.12.0/22,10.128.16.0/22
       # InstanceType used for NAT instances
       InstanceType: ${nat_instance_type}
       SshKeyName: ${ssh_key_name}

**Comment by phobologic** [comment]
Cool - I made some updates here with the new AMI:

https://github.com/remind101/stacker/pull/116

Let me know if that looks ok to you.

**Comment by phobologic** [comment]
OK, I think #116 should cover it - I'm going to go ahead and close this.  If you have issues with ti, let me know.
