### ISSUE TITLE
Issue force updating new RDS Db

### ISSUE THREAD

**Issue by mhahn** [remind101/stacker#96]
```
CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename apirdsdb and update the stack again.
```

i know its rare that you want to update a db and replace it, but in this case i did. not sure if we care about handling it.

**Comment by phobologic** [comment]
This has been a bit, but I'm curious what you updated that caused it to have to replace it?

**Comment by phobologic** [comment]
Closing this for now - if it pops up again, we can investigate (also, should probalby be in stacker_blueprints now).
