### ISSUE TITLE
Started seeing issues with TCS with new amis

### ISSUE THREAD

**Issue by mhahn** [remind101/stacker#97]
https://github.com/aws/amazon-ecs-agent/issues/102

**Comment by rafaelmagu** [comment]
Is there an IAM permission missing? I'm seeing the same issue, but couldn't find any documentation on why it's there. I don't know if `ECS_DISABLE_METRICS=true` also stops CloudWatch.

**Comment by phobologic** [comment]
I actually have a fix for this - I'm working on rolling it out today.  Basically ECS has a bunch of undocumented volumes that it needs to get stats.

See:

https://github.com/remind101/empire_ami/pull/6

I'm going to go ahead and close this issue here, lets track it in that PR.

**Comment by crohr** [comment]
@phobologic is there also the need for updating the minion policy to allow `ecs:StartTelemetrySession`?

**Comment by phobologic** [comment]
Actually yes - that's in my latest round of updates that are on-deck.  Just waiting to get logging in the AMI, then I'll have a set of new releases (for both stacker & the empire_ami) that will make it easy to get logging going.

**Comment by phobologic** [comment]
Hey guys - I've gone ahead and finished building the new AMIs, and have updated stacker to use the new AMIs.  I haven't yet done a new release of stacker, but if you use the version in git you should be able to test this.  Out of the box we enable log streaming, but it can be disabled in the environment file.  Note - there is a new environment setting:

```
# Change to anything non-blank to disable streaming logs (enabled by default)
empire_disable_streaming_logs: "''"
```

If folks could give it a try, that'd be awesome.  It worked the 3 times I've tested it so far.

**Comment by crohr** [comment]
Thanks @phobologic, I'll be able to test the new images next week and will report back.

**Comment by crohr** [comment]
@phobologic sorry for the late update, but updated our platform last week, and log streaming works like a charm, as well as telemetry. Thanks!

**Comment by phobologic** [comment]
Cool - I'm going to go ahead and spin a new release of stacker for this.  Thanks!

**Comment by phobologic** [comment]
This was pulled into 0.5.3!  Closing.
